name: iChat
main: net.TheDgtl.iChat.iChat
version: 2.3.3-p3
depend: [Permissions]
author: Drakia
website: http://thedgtl.net/
commands:
  ichat:
    description: Used to reload the plugin.
    usage: /<command> reload - Used to reload the plugin.