name: iChat
main: net.TheDgtl.iChat.iChat
version: 2.4.4
author: Drakia
website: http://thedgtl.net/
commands:
  ichat:
    description: Used to reload the plugin.
    usage: /<command> reload - Used to reload iChat's config
softdepend: [bPermissions, Permissions, PermissionsBukkit, PermissionsEx]